const imageLinks = {
  bug: 'icons/bug.svg',
  grass:'icons/grass.svg',
  fire: 'icons/fire.svg',
  poison: 'icons/poison.svg',
  water: 'icons/water.svg',
  flying: 'icons/flying.svg',
  normal: 'icons/normal.svg',
  ice: 'icons/ice.svg',
  steel: 'icons/steel.svg',
  rock: 'icons/rock.svg',
  electric: 'icons/electric.svg',
  ground: 'icons/ground.svg',
  fairy: 'icons/fairy.svg',
  ghost: 'icons/ghost.svg',
  fighting: 'icons/fighting.svg',
  dark: 'icons/dark.svg',
}
